name: Tie breaker unit tests

on: push

env:
  MCC_TESTING: 1
  MCC_TEST_TYPE: MCC_TEST_3TEAM_TIE
  RESULTS_MD5: 21765c30ba63d2f213a3b99f37a3223c
  
defaults:
  run:
    shell: bash

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.x
        uses: actions/setup-python@v3
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.x'
      # You can test your matrix by printing the current Python version
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install dependencies
        run: python -m pip install --upgrade pip cfbd
      - name: Run the code
        run: python vconf/mcc_schedule.py -s 1970 -e 1970 -v >& output.txt
      - name: md5_results
        run: /usr/bin/md5sum output.txt
      - name: show_full_results
        run: /usr/bin/cat output.txt
      - name: Check md5
        id: check_md5
        run: echo "::set-output name=md5_out::"`/usr/bin/md5sum output.txt | /usr/bin/cut -d ' ' -f 1`
      - name: Pass or fail
        run: |
          if [[ "${{ steps.check_md5.outputs.md5_out }}" == "$RESULTS_MD5" ]]; then exit 0; else exit 1; fi
